"""Add sender_account, receiver_account, notes to Transaction

Revision ID: 878fa849bb50
Revises: b9494684b3df
Create Date: 2025-09-05 14:12:54.249275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878fa849bb50'
down_revision: Union[str, Sequence[str], None] = 'b9494684b3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_clean')
    op.drop_table('customers_accounts_clean')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_account', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_account', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('receiver_account')
        batch_op.drop_column('sender_account')

    op.create_table('customers_accounts_clean',
    sa.Column('Customer', sa.TEXT(), nullable=True),
    sa.Column('Address', sa.TEXT(), nullable=True),
    sa.Column('Phone', sa.TEXT(), nullable=True),
    sa.Column('Personnummer', sa.TEXT(), nullable=True),
    sa.Column('BankAccount', sa.TEXT(), nullable=True)
    )
    op.create_table('transactions_clean',
    sa.Column('transaction_id', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=True),
    sa.Column('sender_account', sa.TEXT(), nullable=True),
    sa.Column('receiver_account', sa.TEXT(), nullable=True),
    sa.Column('sender_country', sa.TEXT(), nullable=True),
    sa.Column('sender_municipality', sa.TEXT(), nullable=True),
    sa.Column('receiver_country', sa.TEXT(), nullable=True),
    sa.Column('receiver_municipality', sa.TEXT(), nullable=True),
    sa.Column('transaction_type', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
