"""test

Revision ID: b9494684b3df
Revises: 65e60fb6b172
Create Date: 2025-09-03 23:21:59.463020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9494684b3df'
down_revision: Union[str, Sequence[str], None] = '65e60fb6b172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_clean')
    op.drop_table('customers_accounts_clean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_accounts_clean',
    sa.Column('Customer', sa.TEXT(), nullable=True),
    sa.Column('Address', sa.TEXT(), nullable=True),
    sa.Column('Phone', sa.TEXT(), nullable=True),
    sa.Column('Personnummer', sa.TEXT(), nullable=True),
    sa.Column('BankAccount', sa.TEXT(), nullable=True)
    )
    op.create_table('transactions_clean',
    sa.Column('transaction_id', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=True),
    sa.Column('sender_account', sa.TEXT(), nullable=True),
    sa.Column('receiver_account', sa.TEXT(), nullable=True),
    sa.Column('sender_country', sa.TEXT(), nullable=True),
    sa.Column('sender_municipality', sa.TEXT(), nullable=True),
    sa.Column('receiver_country', sa.TEXT(), nullable=True),
    sa.Column('receiver_municipality', sa.TEXT(), nullable=True),
    sa.Column('transaction_type', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
